name    'erwbgy-pamldap'
version '0.1.0'
source 'https://github.com/erwbgy/puppet-pamldap.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Use LDAP for user login/authentication/authorisation/name resolution'
description 'Use LDAP for user login/authentication/authorisation/name resolution'
project_page 'git.com:erwbgy/puppet-pamldap.git'
